import { EmpleadoEntity } from "./empleado.entity";
import {Categorias,Educacion,Domicilio,Jornadas,Liquidacion} from "./empleado.interface";

export class EmpleadoValue implements EmpleadoEntity{
    nombre:string;
    apellido:string;
    edad:number;
    cuil:string;
    dni:string;
    sexo:string;
    legajo:number;
    email:string;
    telefono:string;
    domicilio:Domicilio[];
    fecha_ingreso:string;
    fecha_egreso: string;
    nivel_educacion:Educacion[];
    activo:boolean;
    convenio:string;
    contratacion:string;
    categoria:Categorias[];
    gerencia:string;
    area:string;
    sector:string;
    puesto:string;
    rol:string;
    tipo_liquidacion: string;
    rotacion: string;
    grupo: string;
    turno: string;
    jornada:Jornadas[];
    liquidacion:Liquidacion[];
    observaciones:string;
    foto:string;
    constructor({    
        nombre,
        apellido,
        edad,
        cuil,
        dni,
        sexo,
        legajo,
        email,
        telefono,
        domicilio,
        nivel_educacion,
        fecha_ingreso,
        fecha_egreso,
        activo,
        convenio,
        contratacion,
        categoria,
        gerencia,
        area,
        sector,
        puesto,
        rol,
        tipo_liquidacion,
        rotacion,
        turno,
        grupo,
        jornada,
        foto,
        liquidacion,
        observaciones,
        }:{    
        nombre:string;
        apellido:string;
        edad:number;
        cuil:string;
        dni:string;
        sexo:string;
        legajo:number;
        email:string;
        telefono:string;
        domicilio:Domicilio[];
        fecha_ingreso:string;
        fecha_egreso:string;
        nivel_educacion:Educacion[];
        activo:boolean;
        convenio:string;
        contratacion:string;
        categoria:Categorias[];
        gerencia:string;
        area:string;
        sector:string;
        puesto:string;
        rol:string;
        tipo_liquidacion:string;
        rotacion:string;
        turno:string;
        grupo:string;
        jornada:Jornadas[];
        liquidacion:Liquidacion[];
        observaciones:string;
        foto:string;
        }){
            this.nombre=nombre
            this.apellido=apellido
            this.edad=edad
            this.cuil=cuil
            this.dni=dni
            this.sexo=sexo
            this.legajo=legajo
            this.email=email
            this.telefono=telefono
            this.domicilio=domicilio
            this.fecha_ingreso=fecha_ingreso
            this.fecha_egreso=fecha_egreso
            this.nivel_educacion=nivel_educacion
            this.activo=activo
            this.convenio=convenio
            this.contratacion=contratacion
            this.categoria=categoria
            this.gerencia=gerencia
            this.area=area
            this.sector=sector
            this.puesto=puesto
            this.rol=rol
            this.tipo_liquidacion=tipo_liquidacion
            this.rotacion=rotacion
            this.grupo=grupo
            this.turno=turno
            this.jornada=jornada
            this.foto=foto
            this.liquidacion=liquidacion
            this.observaciones=observaciones
        }
}